/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exchange */

#ifndef _Included_Exchange
#define _Included_Exchange
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exchange
 * Method:    getMailbox
 * Signature: ()Ljava/util/Hashtable;
 */
JNIEXPORT jobject JNICALL Java_Exchange_getMailbox
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
